<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latestmajor</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KUKULCAN.SharedKernel" Version="1.0.0" />
    <PackageReference Include="KUKULCAN.SharedKernel.Auth" Version="1.0.0" />
    <PackageReference Include="KUKULCAN.SharedKernel.Database" Version="1.0.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0" />
  </ItemGroup>
</Project>
